blog/urls.py
app_name='blog'
from django.urls import path, re_path
from blog import views

urlpatterns = [
    path('index/', views.index, name='blog_index'),
    path('get_category_data/', views.get_category_data, name='get_category_data'),
    re_path('list/(?P<slug>[^\.]+)/', views.list_category, name ='list_category'),
    re_path('(?P<slug>[^\.]+).html', views.blog_detail, name='blog_view'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from homepage import views
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

auth_patterns = [
	path('login/', auth_views.login, {'template_name': 'index/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'index/logged_out.html', 'next_page': 'index'}, name='logout'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('auth/', include(auth_patterns)),
    path('blog/', include("blog.urls")),
    path('info/', include("info.urls")),
    path('stock/', include("stock.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/urls.py
app_name='info'
from django.urls import path, re_path
from info import views

urlpatterns = [
    path('get_menu_data/', views.get_menu_data, name="get_menu_data"),
]

stock/urls.py
app_name='stock'
from django.urls import path, re_path
from stock import views

urlpatterns = [
    path('index/', views.index, name='stock_index'),
    path('get_menu_data/', views.get_menu_data, name='get_menu_data'),
    #股票名称
    path('name_file/', views.name_file, name='name_file'),
    path('upload_name_file', views.upload_name_file, name='upload_name_file'),
    path('update_name/', views.update_name, name='update_name'),
    path('name_data/', views.name_data, name='name_data'),
    re_path('name_data/(?P<stockcode>[0-9]{1,6})/', views.name_data_by_code, name='name_data_by_code'),
    #每日股票数据
    path('pricedaily_data/',views.pricedaily_data, name='pricedaily_data'),
    re_path('pricedaily_data/(?P<stockcode>[0-9]{1,6})/', views.pricedaily_data_by_code, name='pricedaily_data_by_code'),
    path('download_pricedaily_csv/', views.download_pricedaily_csv, name='download_pricedaily_csv'),
    path('updatecsv2database/', views.updatecsv2database, name='updatecsv2database'),
    path('delete_pricedaily_csv/', views.delete_pricedaily_csv, name='delete_pricedaily_csv'),
    path('progress/', views.progress, name='progress'),
    #大单交易数据
    path('dadang_exchange/', views.dadang_exchange, name='dadang_exchange'),
    re_path('dadang_exchange/(?P<stockcode>[0-9]{1,6})/', views.dadang_exchange_by_code, name='dadang_exchange_by_code'),
    path('update_dadang_exchange/', views.update_dadang_exchange, name='update_dadang_exchange'),
    #数据可视化
    re_path('graphic/(?P<code>[0-9]{6})/', views.graphic, name = 'graphic'),
    path('stock_contrast/', views.stock_contrast, name='stock_contrast'),
    path('get_stock_code/', views.get_stock_code, name='get_stock_code'),
    path('get_contrast_data/', views.get_contrast_data, name='get_contrast_data'),
]

templates/index/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ MEDIA_URL }}pic/favicon.ico">

    <title>Django应用</title>

    {% load staticfiles %}
	<!-- core CSS -->
	<link href="{% static 'bootstrap-4.1.1/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-4.1.1/css/jumbotron.css' %}" rel="stylesheet">
	<link href="{% static 'other/css/index.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Django应用</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        </ul>
      </div>
	  <div id="login">
		{% if user.is_authenticated %}
		  <a href="/admin">{{ user.username }}!</a>
		  <a href="{% url 'logout' %}">退出</a>
		  {% else %}
		  <a href="{% url 'login' %}">登录</a>
		  {% endif %}
		</div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Django应用</h1>
          <p>Django是一个开放源代码的Web应用框架，由Python写成。采用了MVC的框架模式，即模型M，视图V和控制器C。它最初是被开发来用于管理劳伦斯出版集团旗下的一些以新闻内容为主的网站的，即是CMS（内容管理系统）软件。并于2005年7月在BSD许可证下发布。这套框架是以比利时的吉普赛爵士吉他手Django Reinhardt来命名的。</p>
          <p><a class="btn btn-primary btn-lg" href="https://baike.baidu.com/item/django/61531?fr=aladdin" role="button" target="_blank">了解更多 &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-6">
            <h2>博客</h2>
            <p>作为一个设计方面的学徒，我仍在持续学习中。我将数据可视化与信息技术相结合来展示数据，将 UI 与前端相结合来创建更好的用户体验，将设计引入技术来创建价值。 </p>
            <p><a class="btn btn-secondary" href="{% url 'blog:blog_index' %}" role="button">进入系统 &raquo;</a></p>
          </div>
          <div class="col-md-6">
            <h2>StockAns</h2>
            <p>作为一个程序员、软件咨询师，我拥有广泛的技术栈：前端领域、物联网领域、移动开发（混合应用、Android 原生）、后台开发。 作为一个活跃的社区贡献者，我长期活跃于GitHub，并创建了相当数量的开源项目。 </p>
            <p><a class="btn btn-secondary" href="{% url 'stock:stock_index' %}" role="button">进入系统 &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; 向着太阳&nbsp;Email:2463772128@qq.com</p>
    </footer>

    <!-- core JavaScript -->
    <script src="{% static 'bootstrap-4.1.1/js/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript">
		function createNode(data){
			node = ''
			for(var i=0; i < data.length; i++){
				if(data[i]["children"]){
					node += '<li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="'+data[i]["href"]+'"  id="'+data[i]["id"]+'" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'+data[i]["text"]+'</a><div class="dropdown-menu" aria-labelledby="'+data[i]["id"]+'">'
					node += createNode(data[i]["children"]);
					node += '</div></li>'
				}
				else if (data[i]["id"].length == 3){
					node += '<li class="nav-item"><a class="nav-link" href="'+data[i]["href"]+'">'+data[i]["text"]+'</a></li>'
				}
				else{
					node += '<a class="dropdown-item" href="'+data[i]["href"]+'">'+data[i]["text"]+'</a>'
				}
			}
			return node;
		}
		$(document).ready(function () {
			$.get("{% url 'info:get_menu_data' %}", function(data){
				var node_str = createNode(data);
				$(".navbar-nav").append(node_str);
			})
		});
    </script>
  </body>
</html>

templates/index/logged_out.html
{% extends 'login_base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/index/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>登录</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'other/css/login.css' %}">
</head>
<body>
  <header>
    <h1>Django应用</h1>
  </header>
  <hr>
  <main>
  <form method="post">
    {% csrf_token %}
	<div class="login">
	  <label for="id_username">用户名:</label>
		{{ form.username }}
		&nbsp;
		<label for="id_password">密码:</label>
		{{ form.password }}
		<button type="submit">登录</button>
	  </div>
  </form>
  </main>
  <hr>
  <footer>
  </footer>
</body>
</html>

templates/index/login_base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Simple Login{% endblock %}</title>
</head>
<body>
  <header>
    <h1>Django Simple Login</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
  <footer>
    <a href="http://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a>
  </footer>
</body>
</html>

templates/index/password_change_form.html
{% extends 'login_base.html' %}

{% block title %}Passworchange{% endblock %}

{% block content %}
  <h2>Passworchange</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change</button>
  </form>
{% endblock %}

templates/index/password_reset_confirm.html
{% extends 'login_base.html' %}

{% block title %}Passwordreset{% endblock %}

{% block content %}
  <h2>Passwordreset</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset</button>
  </form>
{% endblock %}

templates/index/password_reset_email.html
{% extends 'login_base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
Someone asked for password reset for email {{ email }}. Follow the link below: {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}