blog/urls.py
app_name='blog'
from django.urls import path, re_path
from blog import views

urlpatterns = [
    path('index/', views.index, name='blog_index'),
    path('get_category_data/', views.get_category_data, name='get_category_data'),
    re_path('list/(?P<slug>[^\.]+)/', views.list_category, name ='list_category'),
    re_path('(?P<slug>[^\.]+).html', views.blog_detail, name='blog_view'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from homepage import views
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

auth_patterns = [
	path('login/', auth_views.login, {'template_name': 'index/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'index/logged_out.html', 'next_page': 'index'}, name='logout'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('auth/', include(auth_patterns)),
    path('blog/', include("blog.urls")),
    path('info/', include("info.urls")),
    path('stock/', include("stock.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.db.models import permalink
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
    name = models.CharField('分类名', max_length=30, unique=True)
    slug = models.SlugField('slug', max_length=40)
    parent_category = models.ForeignKey('self', verbose_name='父级分类', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']
        verbose_name = "博客分类"
        verbose_name_plural = "博客分类"

    def __str__(self):
        return self.name

class Blog(models.Model):
    class Meta:
        verbose_name = '博客'
        verbose_name_plural = '博客'

    title = models.CharField(max_length=30, unique=True, verbose_name='标题', help_text='博客的标题')
    category = models.ForeignKey(Category, verbose_name='归类', default=10, on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL')
    body = RichTextUploadingField(verbose_name='正文')
    posted = models.DateField(db_index=True, auto_now_add=True)

    def __str__(self):
        return '%s' % (self.title)

    @permalink
    def get_absolute_url(self):
        return 'blog_view', None, {'slug': self.slug}

blog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json, os, logging

from lib.extend import get_category
from blog.models import Blog, Category

# Create your views here.
def index(request):
    return render_to_response('blog/blog_index.html')

def list_category(request, slug):
    category = Category.objects.get(slug=slug)
    return render_to_response('blog/list.html', {'blogs': category.blog_set.all()})


@csrf_exempt
def get_category_data(request):
    category_root = Category.objects.get(parent_category=None)
    data_json = get_category(category_root.slug)
    return HttpResponse(json.dumps(data_json), content_type='application/json')

def blog_detail(request, slug):
    return render_to_response('blog/detail.html', {'blog': get_object_or_404(Blog, slug=slug)})

templates/blog/blog_index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ MEDIA_URL }}pic/favicon.ico">

    <title>博客首页</title>

    {% load staticfiles %}
	<!-- core CSS -->
	<link href="{% static 'bootstrap-4.1.1/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'jsTree/themes/default/style.min.css' %}" rel="stylesheet">
	<link href="{% static 'other/css/blog_index.css' %}" rel="stylesheet">
  </head>

  <body>
	  <div class="container-fluid">
		  <div class="row">
			  <div class="col-md-2 col-12" id="category">
		  	  </div>
			  <div class="col-md-10 col-12">
				   <iframe name='main' id="iframepage" frameborder="0" ></iframe>
			  </div>
		  </div>
	  </div>
    <!-- core JavaScript -->
    <script src="{% static 'bootstrap-4.1.1/js/vendor/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'jsTree/jstree.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript">
	$(function () {
		$("#category").jstree({
			'core':{
				'data':{
					"url":"{% url 'blog:get_category_data' %}",
					"dataType":"json"
				}
			}
		});
		$("#category").on("changed.jstree", function(e, data){
			var url = "{% url 'blog:list_category' '000' %}"
			var id = data.selected;
			window.parent.main.location.href = url.replace('000',id);
		});
	});
    </script>
  </body>
</html>

templates/blog/detail.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ blog.title }}</title>
{% load staticfiles %}
<link href="{% static 'other/css/detail.css' %}" rel="stylesheet">
</head>

<body>
<h2>{{ blog.title }}</h2>
<p>{{ blog.body | safe }}</p>
<p>{{ blog.posted }} - By {{ blog.author }}</p>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
</body>
</html>

templates/blog/list.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Growth Studio - Blog</title>
</head>

<body>
	{% for blog in blogs %}
	<h2><a href="{% url 'blog:blog_view' blog.slug %}" target="_blank">{{ blog.title }}</a></h2>
	<p>{{ blog.body | slice:":80" | safe }}</p>
	<p>{{ blog.posted }} - By {{ blog.author }}</p>
	{% endfor %}
</body>
</html>