blog/urls.py
app_name='blog'
from django.urls import path, re_path
from blog import views

urlpatterns = [
    path('index/', views.index, name='blog_index'),
    path('get_category_data/', views.get_category_data, name='get_category_data'),
    re_path('list/(?P<slug>[^\.]+)/', views.list_category, name ='list_category'),
    re_path('(?P<slug>[^\.]+).html', views.blog_detail, name='blog_view'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from homepage import views
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

auth_patterns = [
	path('login/', auth_views.login, {'template_name': 'index/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'index/logged_out.html', 'next_page': 'index'}, name='logout'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('auth/', include(auth_patterns)),
    path('blog/', include("blog.urls")),
    path('info/', include("info.urls")),
    path('stock/', include("stock.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
app_name='stock'
from django.urls import path, re_path
from stock import views

urlpatterns = [
    path('index/', views.index, name='stock_index'),
    path('get_menu_data/', views.get_menu_data, name='get_menu_data'),
    #股票名称
    path('name_file/', views.name_file, name='name_file'),
    path('upload_name_file', views.upload_name_file, name='upload_name_file'),
    path('update_name/', views.update_name, name='update_name'),
    path('name_data/', views.name_data, name='name_data'),
    re_path('name_data/(?P<stockcode>[0-9]{1,6})/', views.name_data_by_code, name='name_data_by_code'),
    #每日股票数据
    path('pricedaily_data/',views.pricedaily_data, name='pricedaily_data'),
    re_path('pricedaily_data/(?P<stockcode>[0-9]{1,6})/', views.pricedaily_data_by_code, name='pricedaily_data_by_code'),
    path('download_pricedaily_csv/', views.download_pricedaily_csv, name='download_pricedaily_csv'),
    path('updatecsv2database/', views.updatecsv2database, name='updatecsv2database'),
    path('delete_pricedaily_csv/', views.delete_pricedaily_csv, name='delete_pricedaily_csv'),
    path('progress/', views.progress, name='progress'),
    #大单交易数据
    path('dadang_exchange/', views.dadang_exchange, name='dadang_exchange'),
    re_path('dadang_exchange/(?P<stockcode>[0-9]{1,6})/', views.dadang_exchange_by_code, name='dadang_exchange_by_code'),
    path('update_dadang_exchange/', views.update_dadang_exchange, name='update_dadang_exchange'),
    #数据可视化
    re_path('graphic/(?P<code>[0-9]{6})/', views.graphic, name = 'graphic'),
    path('stock_contrast/', views.stock_contrast, name='stock_contrast'),
    path('get_stock_code/', views.get_stock_code, name='get_stock_code'),
    path('get_contrast_data/', views.get_contrast_data, name='get_contrast_data'),
]

stock/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    name = models.CharField('菜单名', max_length=30, unique=True)
    href = models.CharField('链接地址', max_length=30, default="#")
    slug = models.SlugField('slug', max_length=40)
    parent_menu = models.ForeignKey('self', verbose_name='父级菜单', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']
        verbose_name = "菜单设置"
        verbose_name_plural = "菜单设置"

    def __str__(self):
        return self.name

class Name(models.Model):
	companycode = models.CharField(max_length = 10)
	companyabb = models.CharField(max_length = 10)
	stockexchangeno= models.CharField(max_length = 10)
	stockstyle = models.CharField(max_length = 10)
	stockcode = models.CharField(max_length = 10)
	stockabb = models.CharField(max_length = 10)
	listingdate = models.DateField(null=True)
	generalcapital = models.FloatField()
	circulatingcapital = models.FloatField()
	bysector = models.CharField(max_length = 10)
	filename = models.CharField(max_length = 10, null=True)
	startdate = models.DateField(null = True)
	enddate = models.DateField(null=True)
	fupdatetime = models.DateField(null=True)

	def __str__(self):
		return self.stockabb

	class Meta:
		permissions = (
			('views_name_manage', '名称管理'),
		)
		verbose_name = "股票名称"
		verbose_name_plural = "股票名称"

class Pricedaily(models.Model):
	date = models.DateField(null=True)
	tclose = models.FloatField(null=True)
	high = models.FloatField(null=True)
	low = models.FloatField(null=True)
	topen = models.FloatField(null=True)
	lclose = models.FloatField(null=True)
	chg = models.FloatField(null=True)
	pchg = models.FloatField(null=True)
	voturnover = models.FloatField(null=True)
	vaturnover = models.FloatField(null=True)
	stockname = models.ForeignKey(Name, on_delete=models.CASCADE)

	def __str__(self):
		return self.stockname

	class Meta:
		permissions = (
			('views_price_data_manage', '价格数据管理'),
		)
		verbose_name = '每日价格'
		verbose_name_plural = '每日价格'

class Bigexchange(models.Model):
	date = models.DateField(null=True)
	zhulj = models.FloatField(null=True)
	zhuljper = models.FloatField(null=True)
	chaodd = models.FloatField(null=True)
	chaoddper = models.FloatField(null=True)
	dd = models.FloatField(null=True)
	ddper = models.FloatField(null=True)
	zd = models.FloatField(null=True)
	zdper = models.FloatField(null=True)
	xd = models.FloatField(null=True)
	xdper = models.FloatField(null=True)
	stockname = models.ForeignKey(Name, on_delete=models.CASCADE)

	def __str__(self):
		return self.stockname

	class Meta:
		permissions = (
			('views_dd_data_manage', '大单数据管理'),
			('views_k_unit_manage', '曲线对比'),
		)
		verbose_name = '大单交易'
		verbose_name_plural = '大单交易'

stock/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect, Http404
from django.views.decorators.csrf import csrf_exempt
import json, glob, os, logging
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Max, Min, Count
import time
from datetime import datetime, date

from lib.extend import get_stock_menu
from lib.manage_stock_name import get_excel_data_dict, update_name_use_dict
from lib.pricedaily_csv import download_pricedaily_file, update_pricedaily_file
from lib.getmoneystream import download_moneystream

from stock.models import Menu,Name

# 生成logger
logger = logging.getLogger(__name__)
logger.setLevel(level=logging.INFO)
handler = logging.FileHandler(os.path.join(settings.MEDIA_ROOT, 'log', 'stock.log'))
handler.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

#进度条数值
per_downloadcsv_progress = 0
per_update_price_progress = 0
per_deletecsv_progress = 0
per_update_dadang_exchange = 0

class CJsonEncoder(json.JSONEncoder):
	#自定义时间json序列化格式
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj, date):
            return obj.strftime("%Y-%m-%d")
        else:
            return json.JSONEncoder.default(self, obj)

# Create your views here.
def index(request):
    '''
    StocAns首页
    :param request:
    无
    :return:
    无
    '''
    return render(request, 'stock/stock_index.html')

def get_menu_data(request):
    '''
    获取StockAns应用首页目录数据
    :param request:
    无
    :return:
    data_json:目录列表数据json序列化
    '''
    menu_root = Menu.objects.filter(parent_menu=None).order_by("slug")
    data_json = []
    for menu in menu_root:
        data_json.append(get_stock_menu(menu.slug))
    return HttpResponse(json.dumps(data_json), content_type='application/json')

def name_file(request):
	'''
	股票名称数据文件
	:param request:
	:return:
	'''
	files = []
	for file in glob.glob(os.path.join(settings.MEDIA_ROOT, 'stockname', '*.xls*')):
		files.append(file)
	return render(request, 'stock/stock_name_file.html', {'files':files})

def upload_name_file(request):
	'''
	上传股票名称xls文件
	:param request:
	:return:
	'''

	# 请求方法为POST时，进行处理
	if request.method == "POST":
		# 获取上传的文件，如果没有文件，则默认为None
		myFile =request.FILES.get("myfile", None)
		if not myFile:
			logger.info("no files for upload!")
			return HttpResponse("no files for upload!")
		else:
			file_suffix = myFile.name.split(".")[-1]
			if file_suffix not in ["xls", "xlsx"]:
				logger.info("uploading file type is not supported!")
				return HttpResponse("uploading file type is not supported!")
			else:
				# 打开特定的文件进行二进制的写操作
				destination = open(os.path.join(settings.MEDIA_ROOT, 'stockname', myFile.name),'wb+')
				# 分块写入文件
				for chunk in myFile.chunks():
					destination.write(chunk)
				destination.close()
				logger.info(myFile.name + "---上传成功！")
				return HttpResponseRedirect("/stock/name_file/")

@csrf_exempt
def update_name(request):
	'''
	更新股票名称
	:param request:
	:return:
	'''
	if request.method=="POST":
		file_excel=request.POST.get("k1")
		action = request.POST.get("action")
	if action == "更新数据":
		data=get_excel_data_dict(file_excel=file_excel, col_name_index=0, by_index=0)
		insert_num = update_name_use_dict(data)
		msg = "成功更新" + str(insert_num) + "数据！"
		logger.info(msg)
	if action == "删除文件":
		try:
			os.remove(file_excel)
			logger.info(file_excel + '---删除成功')
			msg = "文件删除成功！"
		except Exception as e:
			logger.info(file_excel + '---删除错误，错误信息：' + str(e))
			msg = "文件删除错误！"
	return HttpResponse(msg)

def name_data(request):
	'''
	股票名称数据页
	:param request:
	:return:
	'''
	names = Name.objects.all()
	paginator = Paginator(names, 20)
	page = request.GET.get('page')
	try:
		name_list = paginator.page(page)
	except PageNotAnInteger:
		name_list = paginator.page(1)
	except EmptyPage:
		name_list = paginator.page(paginator.num_pages)
	return render(request, 'stock/stock_name_data.html',{ 'stocknames':name_list})

def name_data_by_code(request, stockcode):
	'''
	股票名称数据页，根据股票代码查询数据显示
	:param request:
	:return:
	'''
	names = Name.objects.filter(stockcode__startswith=stockcode)
	paginator = Paginator(names, 20)
	page = request.GET.get('page')
	try:
		name_list = paginator.page(page)
	except PageNotAnInteger:
		name_list = paginator.page(1)
	except EmptyPage:
		name_list = paginator.page(paginator.num_pages)
	return render(request, 'stock/stock_name_data.html',{ 'stocknames':name_list})

def pricedaily_data(request):
	'''
	每日股票价格数据文件
	:param request:
	:return:
	'''
	stock = Name.objects.all().annotate(max_date=Max("pricedaily__date"), min_date=Min("pricedaily__date"))
	paginator = Paginator(stock, 20)
	page = request.GET.get('page')
	try:
		stock_list = paginator.page(page)
	except PageNotAnInteger:
		stock_list = paginator.page(1)
	except EmptyPage:
		stock_list = paginator.page(paginator.num_pages)
	return render(request, 'stock/stock_pricedaily_data.html',{'stocks':stock_list})

def pricedaily_data_by_code(request, stockcode):
	'''
	股票每日价格数据页，根据股票代码查询数据显示
	:param request:
	:return:
	'''
	stock = Name.objects.filter(stockcode__startswith=stockcode).annotate(max_date=Max("pricedaily__date"), min_date=Min("pricedaily__date"))
	paginator = Paginator(stock, 20)
	page = request.GET.get('page')
	try:
		stock_list = paginator.page(page)
	except PageNotAnInteger:
		stock_list = paginator.page(1)
	except EmptyPage:
		stock_list = paginator.page(paginator.num_pages)
	return render(request, 'stock/stock_pricedaily_data.html',{'stocks':stock_list})

@csrf_exempt
def progress(request):
	type = request.POST.get('type')
	if type == "download_pricedaily_data":
		return HttpResponse(str(per_downloadcsv_progress))
	if type == "update_pricedaily_data":
		return HttpResponse(str(per_update_price_progress))
	if type == "delete_csv_file":
		return HttpResponse(str(per_deletecsv_progress))
	if type == "update_dadang_exchange":
		return HttpResponse(str(per_update_dadang_exchange))
	return HttpResponse(str(0))

@csrf_exempt
def download_pricedaily_csv(request):
	'''
	下载每日股票价格数据文件
	:param request:
	:return:
	'''
	# 请求方法为POST时，进行处理
	if request.method == "POST":
		# 1.获取前端传送的公共信息，初始化进度
		dm = request.POST.get('dm')
		start_date = ''.join(request.POST.get('start_date').split('-'))
		end_date = ''.join(request.POST.get('end_date').split('-'))
		download_path = os.path.join(settings.MEDIA_ROOT, 'pricedaily_csv')
		global per_downloadcsv_progress
		per_downloadcsv_progress = 0
		i = 0

		# 2.获取股票代码列表
		code_list = []
		if dm == 'p':
			code_list = Name.objects.values_list('stockcode', flat=True)
		if dm == 's':
			companycode = request.POST.get('stockcode')
			code_list = json.loads(companycode)
		nlen = len(code_list)

		# # 4.下载股票数据文件,更新数据库记录
		for temp_code in code_list:
			stockexchangeno = Name.objects.get(stockcode=temp_code).stockexchangeno
			download = download_pricedaily_file(temp_code, stockexchangeno, start_date, end_date, download_path)
			download.run()
			Name.objects.filter(stockcode=temp_code).update(
				filename=temp_code+'.csv',
				startdate=request.POST.get('start_date'),
				enddate=request.POST.get('end_date'),
				fupdatetime=datetime.now().strftime("%Y-%m-%d"),
			)

			i += 1
			per_downloadcsv_progress = int((i / nlen) * 100)
			msg = '股票：' + temp_code + '，' + start_date + '-' + end_date + '，历史数据文件记录更新成功！'
			logger.info(msg)

			time.sleep(0.05)

	return HttpResponse(None)

@csrf_exempt
def updatecsv2database(request):
	'''
	更新每日股票价格数据文件到数据库
	:param request:
	:return:
	'''
	# 请求方法为POST时，进行处理
	if request.method == "POST":
		# 1.初始化公共信息，初始化进度
		dm = request.POST.get('dm')
		is_colname = True
		col_index = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11]
		global per_update_price_progress
		per_update_price_progress = 0
		i = 0
		nlen = 0

		# 2.获取股票文件列表
		file_list = []
		if dm == 'p':
			stockname_list = Name.objects.all()
			nlen = Name.objects.all().count()
			for stock in stockname_list:
				file_name = os.path.join(settings.MEDIA_ROOT, 'pricedaily_csv', stock.filename)
				file_list.append(file_name)
		if dm == 's':
			name_list_0 = request.POST.get('stockname')
			name_list = json.loads(name_list_0)
			nlen = len(name_list)
			for name in name_list:
				stocks = Name.objects.get(filename=name)
				file_name = os.path.join(settings.MEDIA_ROOT, 'pricedaily_csv', stocks.filename)
				file_list.append(file_name)

		# 4.用数据文件更新数据库
		for file in file_list:
			de = update_pricedaily_file(file, col_index, is_colname=is_colname)
			de.run()

			i += 1
			per_update_price_progress = int((i / nlen) * 100)
			msg = '文件：' + file + '，' + '数据导入成功！'
			logger.info(msg)

			time.sleep(0.05)

	return HttpResponse(None)

@csrf_exempt
def delete_pricedaily_csv(request):
	'''
	删除每日股票价格数据文件
	:param request:
	:return:
	'''
	if request.method == 'POST':
		# 1.获取前端传递的文件列表
		dm = request.POST.get("dm")
		global per_deletecsv_progress
		per_deletecsv_progress = 0
		i = 0
		nlen = 0

		# 2.获取股票文件列表
		name_list = []
		if dm == 'p':
			name_list_origin = Name.objects.values_list('filename', flat=True)
			name_list = [name for name in name_list_origin if name not in ['', ' ', None]]
		if dm == 's':
			name_list_0 = request.POST.get('stockname')
			name_list = json.loads(name_list_0)
		nlen = len(name_list)


		# 3.删除文件，同时记录删除文件记录数据
		for name in name_list:
			file_name = os.path.join(settings.MEDIA_ROOT, 'pricedaily_csv', name)
			if os.path.isfile(file_name):
				try:
					os.remove(file_name)
					Name.objects.filter(filename=name).update(
						filename=None,
						startdate=None,
						enddate=None,
						fupdatetime=datetime.now().strftime("%Y-%m-%d"),
					)
					msg = '文件：' + name + '，' + '删除成功！'
				except Exception  as e:
					msg = '文件：' + name + '，' + '删除错误：' + str(e)

				i += 1
				per_deletecsv_progress = int((i / nlen) * 100)
				logger.info(msg)

templates/stock/stock_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ MEDIA_URL }}pic/favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    {% load staticfiles %}
	<!-- core CSS -->
	<link href="{% static 'bootstrap-4.1.1/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-4.1.1/css/jumbotron.css' %}" rel="stylesheet">
	{% block cssadded %}{% endblock %}
  </head>
  <body style="margin: 0; padding: 0;">
	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}
	<script src="{% static 'bootstrap-4.1.1/js/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.1/js/bootstrap.min.js' %}"></script>
	{% block jsadded %}{% endblock %}
  </body>
</html>

templates/stock/stock_name_file.html
{% extends "stock/stock_base.html" %}
{% block title %}股票名称文件{% endblock %}
{% block cssadded %}
{% load staticfiles %}
<link href="{% static 'other/css/stock_name.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="upload">
  <form enctype="multipart/form-data" action="{% url 'stock:upload_name_file' %}" method="post">
    {% csrf_token %}
    <input type="file" name="myfile" />
    <input type="submit" value="上传文件"/>
  </form>
</div>
<div id="file_list"> {% if files %}
  <table>
    {% csrf_token %}
    {% for file in files %}
    <tr>
      <td>{{ file }}</td>
	  <td><input id="delete_btn" class="file_action" type="button" value="删除文件" rel="{{ forloop.counter }}" /></td>
      <td><input id="update_btn" class="file_action" type="button" value="更新数据" rel="{{ forloop.counter }}" /></td>
    </tr>
    {% endfor %}
  </table>
  {% endif %} </div>
{% endblock %}
{% block jsadded %} 
<script type="text/javascript">
$(document).ready(function(){
  $(".file_action").click(function() {
	  var action = $(this).attr("value")
	  var fileLink = $(this).parent().siblings().html()
	  $.ajax({
		  url: "{% url 'stock:update_name' %}",
		  type: "POST",
		  data: {"k1": fileLink, "action": action},
		  success: function (data) {
			  alert(data);
			  window.location.href = "{% url 'stock:name_file' %}";
			  }
        })
    });
});
</script> 
{% endblock %}

templates/stock/stock_pricedaily_data.html
{% extends "stock/stock_base.html" %}
{% block title %}股票每日价格数据{% endblock %}
{% block cssadded %}
{% load staticfiles %}
<link href="{% static 'other/css/stock_name.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="name_list">
  <div id="name_table">
    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="60" 
        aria-valuemin="0" aria-valuemax="100" style="width: 60%;"> <span id="numprogress"></span> </div>
    </div>
    <div id="operator">
      <div id="name_search">
        <label><span>股票代码：</span></label>
        <input type="text" id="stockcode">
        <input type="button" value="搜索" onClick="search()" />
      </div>
      <div id="time"> <span>开始日期：</span>
        <input id="start_date" name="start_date" type="date" value="2016-01-01" min="2014-01-01" max="2018-12-31" />
        <span>结束日期：</span>
        <input id="end_date" name="end_date" type="date" value="2018-01-01" min="2014-01-01" max="2018-12-31" />
      </div>
      <div id="p_operator">
        <label>批处理操作：</label>
        <input class="downloadcsv" type="button" mode="p" value="下载全部文件" />
        <input class="deletecsv" type="button" mode="p" value="删除全部文件" />
        <input class="updatecsv2database" type="button" mode="p" value="更新全部数据" />
      </div>
      <div id="s_operator">
        <label>单处理操作：</label>
        <input class="downloadcsv" type="button" mode="s" value="下载选中文件" />
        <input class="deletecsv" type="button" mode="s" value="删除选中文件" />
        <input class="updatecsv2database" type="button" mode="s" value="更新选中数据" />
      </div>
    </div>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <td>选择</td>
          <td>序号</td>
          <td>股票代码</td>
          <td>股票简称</td>
          <td>数据起时间</td>
          <td>数据止时间</td>
          <td>文件名称</td>
          <td>文件更新时间</td>
        </tr>
      </thead>
      <tbody>
      
      {% if stocks %}
      {% for stock in stocks %}
      <tr>
        <td class="stock_check"><input class="choice" type="checkbox" /></td>
        <td>{{ stock.id }}</td>
        <td>{{ stock.stockcode }}</td>
        <td>{{ stock.stockabb }}</td>
        <td>{{ stock.min_date }}</td>
        <td>{{ stock.max_date }}</td>
        <td>{{ stock.filename }}</td>
        <td>{{ stock.fupdatetime }}</td>
      </tr>
      {% endfor %}
      {% endif %}
        </tbody>
      
    </table>
  </div>
  <div id="paginator" class="pagination-simple" align="center"> 
    <!-- 如果当前页还有上一页，显示一个上一页的按钮 --> 
    {% if stocks.has_previous %} <a href="?page={{ stocks.previous_page_number }}">上一页</a> {% endif %} 
    <!-- 显示当前页面信息 --> 
    <span class="current">第 {{ stocks.number }} 页 / 共 {{ stocks.paginator.num_pages }} 页</span> 
    <!-- 如果当前页还有下一页，显示一个下一页的按钮 --> 
    {% if stocks.has_next %} <a href="?page={{ stocks.next_page_number }}">下一页</a> {% endif %}
    &nbsp;
    <input type="text" class="page_num" />
    <span>&nbsp;页</span>
    <input class="page_btn" type="button" value="跳转" onclick="page_change()" />
  </div>
</div>
{% endblock %}
{% block jsadded %} 
<script type="text/javascript">
function page_change(){
	var page_num = document.getElementsByClassName("page_num").item(0).value;
	window.location.href = "?page=" + page_num;
	}
function search(){
		var stockcode = document.getElementById("stockcode").value;
		var url = "{% url 'stock:pricedaily_data' %}" + stockcode + "/";
		window.location.href = url;
}
function getprogressnum(tp){
	$.ajax({
		url: "{% url 'stock:progress' %}",
		type: "POST",
		data:{"type":tp},
		success: function (data) {
			if(data == "100")
			{
				window.location.reload();
				window.clearInterval(timer);
			}
			else
			{
				$(".progress-bar").css("width", data+"%");
				document.getElementById("numprogress").innerHTML = data+"%";
			}
		}
	})
}
function startprogress(tp){
	$(".progress").css("display", "block");
	$(".progress-bar").css("width","0%");
	document.getElementById("numprogress").innerHTML = "0%";
	var timer=self.setInterval(getprogressnum,60,tp);
	}
$(document).ready(function(){
	$(".downloadcsv").click(function(){
		var start_date = document.getElementById("start_date").value;
		var end_date = document.getElementById("end_date").value;
		var mode = $(this).attr("mode");
		if(mode == "p"){
			$.ajax({
				url: "{% url 'stock:download_pricedaily_csv' %}",
				type: "POST",
				data: {"dm":"p","start_date": start_date, "end_date": end_date},
				success: function (data) {
					
				}
			})
		}
		if(mode=="s"){
			var chk_value =[];
			$('input[class="choice"]:checked').each(function(){
				chk_value.push($(this).parent().nextAll().eq(1).text());
			});
			$.ajax({
				url: "{% url 'stock:download_pricedaily_csv' %}",
				type: "POST",
				data: {"dm":"s","start_date": start_date, "end_date": end_date,"stockcode":JSON.stringify(chk_value)},
				success: function (data) {
					
				}
			})
		}
		startprogress("download_pricedaily_data")
	})
	$(".updatecsv2database").click(function(){
		var mode = $(this).attr("mode");
		if(mode == "p"){
				$.ajax({
					url: "{% url 'stock:updatecsv2database' %}",
					type: "POST",
					data: {"dm":"p"},
					success: function (data) {
						
					}
				})
		}
		if(mode == "s"){
			var chk_value =[];
			$('input[class="choice"]:checked').each(function(){
				chk_value.push($(this).parent().nextAll().eq(5).text());
			});
			$.ajax({
				url: "{% url 'stock:updatecsv2database' %}",
				type: "POST",
				data: {"dm":"s","stockname":JSON.stringify(chk_value)},
				success: function (data) {
					
				}
			})
		}
		startprogress("update_pricedaily_data")
	})
	$(".deletecsv").click(function(){
		var mode = $(this).attr("mode");
		if(mode == "p"){
			$.ajax({
				url: "{% url 'stock:delete_pricedaily_csv' %}",
				type: "POST",
				data: {"dm":"p"},
				success: function (data) {
					
				}
			})
		}
		if(mode == "s"){
			var chk_value =[]; 
			$('input[class="choice"]:checked').each(function(){
				chk_value.push($(this).parent().nextAll().eq(5).text());
			});
			$.ajax({
				url: "{% url 'stock:delete_pricedaily_csv' %}",
				type: "POST",
				data: {"dm":"s","stockname":JSON.stringify(chk_value)},
				success: function (data) {
					
				}
			})
		}
		startprogress("delete_csv_file")
	})
})
</script> 
{% endblock %}